export const BACK_OFFICE_COPY = {
  adminDesa: {
    common: {
      connectionError: "Koneksi bermasalah. Coba lagi.",
      genericFailed: "Gagal.",
      close: "Tutup",
      cancel: "Batal",
      you: "Kamu",
    },
    badge: {
      dialogLabel: "Status Admin Desa",
      ariaLabel: (status: string) => `Status Admin Desa: ${status}. Klik untuk detail.`,
      status: { verified: "Admin terverifikasi", limited: "Admin terbatas" },
      verifiedItems: ["✓ Dapat mengirim dan memperbarui data desa setelah dokumen lolos review.", "✓ Dapat mengundang admin terbatas.", "✓ Wajib perpanjang verifikasi tiap 6 bulan.", "✗ Tidak punya akses internal admin PantauDesa."],
      limitedItems: ["✓ Diundang oleh admin utama desa.", "✓ Dapat melihat dan mengunggah dokumen.", "✗ Tidak dapat publish data desa.", "✗ Tidak dapat mengundang admin lain."],
      renewal: { overdue: "Perpanjangan terlambat", urgent: "Segera perpanjang", dueSoon: "Perpanjangan akan jatuh tempo", scheduled: "Perpanjangan terjadwal", daysLeft: (days: number) => `${days} hari lagi`, daysLate: (days: number) => `lewat ${Math.abs(days)} hari` },
      note: "Status Admin Desa berbeda dari status data publik. Verifikasi admin tidak otomatis membuat data publik terverifikasi.",
    },
    shell: {
      eyebrow: "Workspace Admin Desa",
      membership: { verified: "Admin terverifikasi", limited: "Admin terbatas" },
      role: { verifiedAdmin: "Bisa kelola anggota", limitedAdmin: "Kontributor dokumen" },
      accountStatus: { title: "Status akun", verifiedBadge: "Verified Resmi", limitedBadge: "Limited Access", verifiedNote: "Badge resmi admin desa aktif", limitedNote: "Masih menunggu penguatan akses" },
      renewal: { title: "Perpanjangan", active: "Aktif", emptyValue: "-", scheduled: "Terjadwal", none: "Belum ada", days: (days: number) => `${Math.abs(days)} hari` },
      backToProfile: "Kembali ke profil saya",
    },
    profile: {
      headingEyebrow: "Profil Admin Desa", headingTitle: "Status dan hak akses kamu", headingBody: (desaName: string) => `Ringkasan peran kamu untuk ${desaName}. Cek status, batas akses, dan jadwal perpanjangan di sini.`, viewPublicProfile: "Lihat profil publik desa", membershipEyebrow: "Status keanggotaan", membership: { verified: "Admin terverifikasi", limited: "Admin terbatas" }, role: { verifiedAdmin: "Admin utama desa", limitedAdmin: "Kontributor dokumen" },
      metrics: { joined: "Bergabung", joinedNote: "Awal akses admin", renewal: "Renewal", renewalOn: "On", renewalOff: "-", renewalInactive: "Belum aktif", days: (days: number) => `${Math.abs(days)} hari`, desa: "Desa", location: "Lokasi lengkap", workArea: "Wilayah kerja admin kamu", inviteAccepted: "Undangan diterima", noInvite: "Tidak melalui undangan", nextRenewal: "Perpanjangan berikutnya", noSchedule: "Belum ada jadwal" },
      currentRole: { title: "Peran kamu saat ini", verified: "Kamu dapat mengelola anggota, menyetujui dokumen admin terbatas, dan mengirim dokumen untuk ditinjau PantauDesa.", limited: "Kamu bisa membantu unggah dokumen. Keputusan penting tetap menunggu admin utama desa." },
      workStandard: { title: "Standar kerja yang disarankan", items: ["Unggah dokumen per topik dan tahun.", "Gunakan judul dokumen yang konsisten.", "Cek notifikasi agar persetujuan tidak menumpuk."] },
      access: { eyebrow: "Hak akses", title: "Yang bisa kamu lakukan", verified: ["Kirim dokumen desa untuk ditinjau PantauDesa.", "Undang dan kelola admin terbatas.", "Setujui dokumen dari admin terbatas sebelum diproses PantauDesa.", "Pantau dokumen, suara warga, dan notifikasi dari workspace ini."], limited: ["Unggah dokumen kontribusi dengan bukti yang jelas.", "Lihat perkembangan dokumen, suara warga, dan pengingat.", "Siapkan dokumen sambil menunggu persetujuan admin utama desa."] },
      limits: { eyebrow: "Pembatas peran", title: "Yang perlu diperhatikan", verified: ["Verifikasi berkala tetap wajib dan tidak otomatis diperpanjang.", "Akses Admin Desa berbeda dari akses internal admin PantauDesa.", "Judul, kategori, dan bukti dokumen membantu review berjalan lebih cepat."], limited: ["Belum bisa publish data desa langsung ke publik.", "Belum bisa mengundang atau mencabut admin lain.", "Dokumen yang dikirim tetap menunggu persetujuan admin utama desa."] },
      renewalAlert: { eyebrow: "Perhatian", overdueTitle: "Perpanjangan terlambat", urgentTitle: "Perpanjangan segera dibutuhkan", body: "Verifikasi Admin Desa perlu diperpanjang berkala. Jika token berhasil dicek, PantauDesa tetap perlu meninjau sebelum masa aktif diperbarui." },
    },
    documents: { headingEyebrow: "Arsip kerja", headingTitle: "Dokumen Desa", summary: { total: "Total", waiting: "Menunggu", published: "Tayang", documents: "dokumen" }, status: { WAITING_VERIFIED_APPROVAL: "Menunggu", PROCESSING: "Diproses", PUBLISHED: "Sudah tayang", REJECTED: "Ditolak", FAILED: "Gagal" }, upload: { eyebrow: "Unggah dokumen", title: "Tambah dokumen", titleLabel: "Judul dokumen", titlePlaceholder: "Contoh: APBDes 2026", categoryLabel: "Kategori", attachmentLabel: "Lampiran", responsibility: "Saya menyatakan dokumen yang diunggah benar dan dapat dipertanggungjawabkan.", storageNotConfiguredTitle: "Storage belum terkonfigurasi", storageNotConfiguredBody: "Unggah dan preview akan ditolak. Hubungi admin PantauDesa.", storageNotReadyShort: "Storage belum siap. Hubungi admin PantauDesa untuk konfigurasi.", uploading: "Mengunggah...", uploadDocument: "Unggah Dokumen", uploadMultipleDocuments: (count: number) => `Unggah ${count} Dokumen`, helper: (maxFileSizeMB: number, maxFilesPerUpload: number, formats: string) => `Maks ${maxFileSizeMB} MB/file, ${maxFilesPerUpload} file/unggah. Format: ${formats}.`, maxFilesError: (maxFilesPerUpload: number) => `Maksimal ${maxFilesPerUpload} file per unggah.`, missingStorageDetail: (env: string) => `Env belum diisi: ${env}.`, invalidStorageDetail: (env: string) => `Format env tidak valid: ${env}.`, storageNotReady: (detail: string) => `Storage belum siap. ${detail}`, chooseFileError: "Pilih minimal satu file.", responsibilityError: "Centang pernyataan tanggung jawab sebelum unggah.", fileTooLargeError: (fileName: string, maxFileSizeMB: number) => `"${fileName}" melebihi batas ${maxFileSizeMB} MB.`, fileTypeError: (fileName: string) => `"${fileName}": tipe file tidak diizinkan.`, uploadFailed: "Gagal mengunggah.", serverNoConfirmation: "Server tidak mengembalikan konfirmasi. Coba refresh lalu cek daftar dokumen.", uploadSuccess: (count: number) => `${count} dokumen berhasil diunggah.` }, list: { title: "Daftar dokumen", empty: "Belum ada dokumen." }, failedReasonLabel: "Alasan:", rejectedReasonLabel: "Alasan penolakan:", rejectModal: { title: "Tolak dokumen", body: "Dokumen yang ditolak akan berhenti di sini. Pengunggah limited harus unggah dokumen baru setelah menerima alasan yang jelas.", reasonLabel: "Alasan penolakan", reasonPlaceholder: "Jelaskan kenapa dokumen ini belum bisa diteruskan.", submit: "Tolak dokumen", submitting: "Menyimpan...", required: "Alasan penolakan wajib diisi." }, actions: { preview: "Preview", approve: "Setujui", reject: "Tolak", closeReject: "Batal", forwardedToPantauDesa: "Dokumen diteruskan ke PantauDesa.", rejectSuccess: "Dokumen berhasil ditolak." } },
    listAdmin: { headingEyebrow: "Kelola anggota", headingTitle: "Tim Admin Desa", inviteButton: "Undang Admin", summary: { active: "Admin aktif", verified: "Verified", limited: "Terbatas", invites: "Undangan" }, roleStatus: { VERIFIED: "Admin terverifikasi", LIMITED: "Admin terbatas", REVOKED: "Akses dicabut", EXPIRED: "Masa aktif berakhir" }, notices: { onlyMainAdminCanManage: "Hanya admin utama desa yang dapat mengundang atau mencabut akses admin lain.", inviteLimitReached: (maxAdmins: number) => `Batas ${maxAdmins} admin aktif sudah tercapai. Cabut salah satu admin terbatas jika ingin membuka slot baru.` }, activeSection: { eyebrow: "Anggota aktif", title: "Struktur tim yang sedang bekerja", empty: "Belum ada admin aktif." }, inviteSection: { eyebrow: "Undangan", title: "Undangan yang masih menunggu", expired: "Sudah kedaluwarsa", pending: "Pending", expiredShort: "Expired", validUntil: (date: string) => `Berlaku sampai ${date}`, sentAt: (date: string) => `Dikirim ${date}` }, historySection: { eyebrow: "Riwayat", title: "Akses yang sudah berakhir", revokedWithReason: (date: string, reason: string) => `Dicabut pada ${date} karena ${reason}` }, modal: { eyebrow: "Aksi admin", inviteTitle: "Undang Admin Desa", inviteSubtitle: (desaName: string) => `Undangan baru untuk ${desaName}`, inviteNotice: "Undangan ini memberi akses awal sebagai admin terbatas. Setelah itu, pengguna tetap perlu melalui verifikasi lanjutan.", inviteEmailLabel: "Email invitee", inviteEmailPlaceholder: "email@desa.id", inviteHelper: "Sistem akan memblokir undangan jika email ini sudah aktif sebagai Admin Desa di desa lain.", sendInvite: "Kirim Undangan", sendingInvite: "Mengirim...", inviteSuccess: "Undangan berhasil dikirim. Calon admin akan menerima tautan untuk menerima undangan.", inviteFailed: "Gagal mengirim undangan.", emailRequired: "Email wajib diisi.", revokeTitle: "Cabut akses admin", revokeNotice: "Akses akan diubah menjadi REVOKED. Riwayat audit dan dokumen yang pernah diunggah tetap tersimpan.", revokeReasonLabel: "Alasan pencabutan", revokeReasonPlaceholder: "Contoh: Tidak lagi bertugas sebagai pengelola data desa.", revokeButton: "Hapus Akses", revokeLoading: "Memproses...", revokeSuccess: "Akses admin berhasil dicabut.", revokeFailed: "Gagal mencabut akses." }, actions: { revokeAriaLabel: (name: string) => `Hapus akses ${name}` } },
    notifications: { summary: { total: "Total", unread: "Belum baca" }, actions: { markAllRead: "Tandai semua baca", markOneRead: "Baca" }, messages: { markAllReadSuccess: "Semua notifikasi ditandai dibaca.", markAllReadFailed: "Gagal.", markOneReadSuccess: "Notifikasi ditandai dibaca.", markOneReadFailed: "Gagal." }, empty: "Belum ada notifikasi.", newBadge: "Baru" },
    suara: { category: { infrastruktur: "Infrastruktur", bansos: "Bansos", fasilitas: "Fasilitas", anggaran: "Anggaran", lingkungan: "Lingkungan", lainnya: "Lainnya" }, status: { OPEN: "Terbuka", IN_PROGRESS: "Sedang ditangani", RESOLVED: "Selesai" }, headingEyebrow: "Suara warga", headingTitle: "Masukan warga untuk desa ini", headingBody: (desaName: string) => `Ringkasan suara warga di ${desaName}. Gunakan halaman ini untuk memahami masukan tanpa mengubah ruang diskusi publik.`, openPublicPage: "Buka suara publik", summary: { total: "Total suara", open: "Terbuka", replies: "Balasan", helpful: "Helpful", publicInput: "masukan publik", unresolved: "belum selesai", discussions: "diskusi tercatat", citizenResponse: "respon warga" }, noticeTitle: "Mode baca", noticeBody: "Tab ini hanya untuk membaca dinamika warga. Balasan dan interaksi tetap dilakukan di halaman publik agar transparan.", empty: "Belum ada suara warga untuk desa ini.", authorAnonymous: "Anonim", labels: { replies: "balasan", helpful: "helpful", vote: "vote", publicArchive: "Arsip publik" }, statusAction: { label: "Tandai status", ariaLabel: (title: string) => `Tandai status untuk: ${title}`, updating: "Menyimpan...", success: "Status berhasil diperbarui.", failed: "Gagal memperbarui status.", consequence: "Status ini membantu warga melihat bahwa masukan sudah ditangani.", options: { OPEN: "Terbuka", IN_PROGRESS: "Sedang ditangani", RESOLVED: "Selesai" } } },
  },
  internalAdmin: { common: {} },
  user: { common: { backToProfile: "Kembali ke profil saya" }, adminClaim: { badge: "Klaim Admin Desa", title: "Ajukan akses admin desa dengan langkah yang jelas.", body: "Pilih desa, pilih cara verifikasi, lalu pantau status pengajuan. Verifikasi admin tidak otomatis membuat data publik desa terverifikasi.", progressTitle: "Lihat progress klaim", stepBadge: (step: number) => `Langkah ${step}/4`, progressSummary: { verified: "Akun sudah menjadi admin terverifikasi.", limited: "Akun punya akses terbatas. Lanjutkan proses jika ingin menjadi terverifikasi.", activeClaim: "Pengajuan aktif sedang diproses.", none: "Belum ada pengajuan aktif." }, inviteDisabledReason: "Undangan admin hanya bisa dikirim oleh admin utama desa." }, profileAdminCard: { eyebrow: "Akses Admin Desa", heading: "Kelola sumber dan dokumen desa lewat akses resmi.", subheading: "Jika kamu perwakilan desa, ajukan akses untuk mengelola informasi sumber dan dokumen desa.", cta: { verified: "Masuk ke Admin Desa", limited: "Masuk ke Admin Desa", pending: "Lihat Status Pengajuan", rejected: "Ajukan Ulang", suspended: "Ajukan Ulang", none: "Klaim sebagai Admin Desa" }, ctaHref: { verified: "/profil/admin-desa/profil", limited: "/profil/admin-desa/profil", pending: "/profil/klaim-admin-desa", rejected: "/profil/klaim-admin-desa", suspended: "/profil/klaim-admin-desa", none: "/profil/klaim-admin-desa" }, contactAdmin: "Hubungi Admin", roleNote: { desa: "Role aplikasi DESA tetap perlu klaim resmi sebelum akses admin desa dibuka.", other: "Akses admin hanya dibuka lewat kanal resmi desa atau bantuan admin PantauDesa." } } },
} as const;

export type BackOfficeCopy = typeof BACK_OFFICE_COPY;
