export const INTAKE_COPY = {
  pageTitle: "Intake Dokumen & Teks",
  pageSubtitle: "Siapkan preview dan kirim ke antrean review internal",
  inputMode: {
    upload: "Upload file",
    paste: "Tempel teks",
    source: "Sumber resmi",
  },
  aiOption: {
    label: "Bantuan AI (opsional)",
    description: "Pakai AI untuk foto, scan, atau dokumen yang sulit dibaca parser lokal",
    checkboxLabel: "Coba AI",
    helperText:
      "Parser lokal tetap dicoba lebih dulu. Jika AI gagal, limit, atau key tidak ada, sistem tetap jujur dan mengarahkan Anda kembali ke parser lokal atau paste teks.",
  },
  desaPicker: {
    label: "Pilih desa (opsional - untuk diff)",
    placeholder: "Ketik nama desa, kecamatan, atau kabupaten",
    selected: "Desa terpilih",
    changeButton: "Ganti",
    noResults: "Tidak ada desa yang cocok.",
    removeLink: "Hapus pilihan desa dan lanjutkan tanpa diff",
    helperText:
      "Admin tidak perlu hafal ID desa. Cukup pilih dari daftar hasil pencarian.",
    disconnectedNote:
      "Jika desa belum dipilih, hasil intake hanya menjadi preview lepas dan tidak terhubung ke data desa mana pun.",
  },
  pipeline: {
    button: "Jalankan pipeline",
    loading: "Memproses...",
  },
  result: {
    mapping: "Mapping",
    validation: "Validasi",
    reviewStatus: "Status Akhir",
    aiHelp: "Bantuan AI",
    notPublishNote: "Belum bisa dipublish dari layar ini.",
  },
  decision: {
    title: "Ringkasan keputusan",
    subtitle: "Jawaban cepat sebelum Anda lanjut",
    targetReview: "Target review",
    mainChanges: "Perubahan utama",
    fieldsRead: "Field terbaca",
    canSubmit: "Bisa kirim sekarang?",
    notSelected: "Belum dipilih",
    noChanges: "Belum terlihat",
    noFields: "Belum ada field",
    guardrailNote:
      "Yang belum terjadi di layar ini: belum submit otomatis, belum publish otomatis, dan belum ada perubahan ke data publik sampai admin menyelesaikan review di antrean.",
  },
  coverage: {
    title: "Cakupan field detail",
    subtitle: "Bandingkan isi upload dengan field yang memang dipakai halaman detail desa",
    filled: "Sudah terisi",
    empty: "Masih kosong",
    covered: "Tercakup upload",
    detectedNotPublishable: "Terdeteksi tapi belum publishable",
    publishableNow: "Publishable sekarang",
    showDetails: "Lihat detail field coverage",
    hideDetails: "Sembunyikan detail field",
    currentValue: "Nilai publik saat ini",
    uploadResult: "Hasil upload",
    source: "Sumber",
    validation: "Validasi",
    notPublishable: "Belum publishable",
    noFindings: "Belum ada temuan yang cukup kuat",
  },
  summary: {
    title: "Apa Yang Terbaca Utama",
    noFields: "Belum ada field utama yang berhasil dibaca otomatis dari dokumen atau teks ini.",
    unmatched: "Masih belum terbaca:",
  },
  validation: {
    title: "Validasi",
    allOk: "Semua field valid.",
    errors: "error",
    warnings: "warning",
  },
  evidence: {
    title: "Bukti Mapping Detail",
    noEvidence: "Tidak ada field yang terdeteksi otomatis.",
    unmatched: "Belum terdeteksi:",
    rule: "rule",
    evidence: "Bukti",
  },
  versionCandidate: {
    title: "Calon Versi Publik",
    status: "Status",
    fieldsChanged: "Field berubah",
    created: "Dibentuk",
    ready: "Siap review",
    published: "Sudah dipublish",
    before: "Sebelum",
    after: "Sesudah",
    draftNote:
      "Snapshot ini siap dibawa ke review internal, belum menjadi data publik.",
  },
  diff: {
    title: "Diff",
    noChanges: "Tidak ada perubahan dari data saat ini.",
    noDesa: "Belum ada desa target",
    noDesaNote: "Pilih desa dari daftar jika ingin membandingkan hasil intake ini dengan data desa yang sudah ada.",
    disconnectedNote: "Tanpa desa terpilih, preview ini tidak akan mengganti, membandingkan, atau mengarahkan perubahan ke desa mana pun.",
  },
  technical: {
    title: "Detail parser lokal & AI",
    inputMode: "Mode input",
    confidence: "Confidence",
    docType: "Tipe dokumen",
    warnings: "Warnings",
    metadata: "Metadata ekstraksi",
    parser: "Parser",
    file: "File",
    size: "Size",
    pages: "Pages",
    sheets: "Sheets",
    duration: "Durasi",
    truncated: "Info",
    truncatedNote: "Teks dipotong",
  },
  review: {
    title: "Langkah 2 · Cek lalu kirim ke review",
    subtitle: "Fokus halaman ini: pastikan hasil otomatisnya masuk akal",
    checkNow: "Yang dicek sekarang",
    checkItems: [
      "1. Apakah desa target sudah benar?",
      "2. Apakah hasil validasi aman?",
      "3. Apakah perubahan utamanya sudah sesuai ekspektasi?",
    ],
    ifOk: "Kalau sudah oke",
    submitted: {
      title: "Hasil intake ini sudah masuk ke antrean review sebagai item `PROCESSING`.",
      queueLink: "Lanjut ke review data",
      newIntake: "Siapkan intake baru",
    },
    submit: {
      label: "Judul item review (opsional)",
      button: "Kirim ke antrean review",
      loading: "Menyimpan ke review...",
      note: "Langkah ini hanya mengirim hasil ke antrean review. Belum publish.",
    },
    guardrails: [
      "Tombol kirim review baru aktif setelah desa target dipilih.",
      "Masih ada error validasi. Perbaiki dulu lalu jalankan pipeline lagi sebelum submit ke review.",
      "Belum ada hasil yang cukup kuat untuk disimpan ke review. Coba aktifkan AI, pilih file lain, atau tempel teks yang lebih jelas.",
    ],
    finalNote: "Publish final tidak terjadi di layar ini. Setelah item masuk ke antrean, admin akan membuka `Review data`, lalu memilih simpan dulu atau publish final.",
  },
  actions: {
    backToInput: "Kembali ke input",
    retry: "Ulangi",
  },
  history: {
    title: "Riwayat Intake & Aktivitas",
    mode: "Mode audit",
    dedicatedActive: "Mode audit dedicated aktif",
    fallbackActive: "Mode fallback audit",
    loading: "Memuat riwayat intake terbaru...",
    empty: "Belum ada intake workbench yang tersimpan ke review internal.",
    submissions: "Submission terbaru",
    submissionsNote: "Klik card untuk membuka dokumen yang sama di antrean review.",
    activity: "Aktivitas audit terbaru",
    goToQueue: "Buka di antrean review",
  },
  versionHistory: {
    title: "Riwayat Versi Desa",
    noDesa: "Pilih desa dulu untuk melihat jejak versi publik internal desa tersebut.",
    mode: "Mode versioning",
    dedicatedActive: "Mode versioning dedicated aktif",
    fallbackActive: "Mode fallback versioning",
    loading: "Memuat riwayat versi desa...",
    empty: "Belum ada versi publik yang tercatat untuk",
    latestPublicNote: "Latest public tetap berasal dari data `Desa`. Riwayat di bawah bersifat internal/audit.",
    lastPublished: "Terakhir dipublikasikan",
    version: "Versi",
  },
  workflow: {
    title: "Alur singkat",
    steps: [
      {
        label: "1. Siapkan bahan",
        note: "Upload file atau tempel teks, lalu pilih desa bila ingin diarahkan ke review.",
      },
      {
        label: "2. Cek hasil otomatis",
        note: "Lihat ringkasan, validasi, perubahan utama, lalu pastikan hasilnya masuk akal.",
      },
      {
        label: "3. Kirim ke antrean review",
        note: "Simpan hasil preview ke antrean internal. Langkah ini belum mengubah data publik.",
      },
      {
        label: "4. Review lalu publish",
        note: "Di antrean review, admin melengkapi data lalu memutuskan publish final.",
      },
    ],
  },
  info: {
    title: "Halaman ini untuk menyiapkan bahan review",
    body: "Di sini Anda cukup membuat preview dan mengirimkannya ke antrean review. Publish final tetap dilakukan nanti dari halaman review data, bukan dari halaman intake ini.",
  },
  aiStatus: {
    title: "Pembacaan AI",
    subtitle: "Jujur tentang kapan AI dipakai dan apa hasilnya",
    noFindings: "Tidak ada temuan AI yang dipakai di draft ini. Preview tetap dibangun dari parser lokal atau dari input manual yang tersedia.",
  },
} as const;
