ALTER TABLE "village_component_catalog"
  ADD COLUMN IF NOT EXISTS "isDefaultVisible" BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS "displayOrder" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "rendererType" TEXT NOT NULL DEFAULT 'identity_grid',
  ADD COLUMN IF NOT EXISTS "previewVariant" TEXT NOT NULL DEFAULT 'identity',
  ADD COLUMN IF NOT EXISTS "detailSlot" TEXT NOT NULL DEFAULT 'first_view',
  ADD COLUMN IF NOT EXISTS "navLabel" TEXT,
  ADD COLUMN IF NOT EXISTS "anchorId" TEXT,
  ADD COLUMN IF NOT EXISTS "publicGroupKey" TEXT,
  ADD COLUMN IF NOT EXISTS "publicTabKey" TEXT,
  ADD COLUMN IF NOT EXISTS "highlightFieldKeys" JSONB,
  ADD COLUMN IF NOT EXISTS "renderConfigJson" JSONB;
