// Canonical audit event type constants for admin claim and internal admin actions.
// All event types are string literals for DB storage flexibility.

export const AUDIT_EVENT = {
  // Claim lifecycle
  CLAIM_STARTED:          "CLAIM_STARTED",
  CLAIM_REUSED:           "CLAIM_REUSED",
  CLAIM_METHOD_UPDATED:   "CLAIM_METHOD_UPDATED",

  // Email verification
  EMAIL_TOKEN_GENERATED:  "EMAIL_TOKEN_GENERATED",
  EMAIL_TOKEN_VERIFIED:   "EMAIL_TOKEN_VERIFIED",
  EMAIL_TOKEN_EXPIRED:    "EMAIL_TOKEN_EXPIRED",
  EMAIL_TOKEN_INVALID:    "EMAIL_TOKEN_INVALID",

  // Website token
  WEBSITE_TOKEN_GENERATED: "WEBSITE_TOKEN_GENERATED",
  WEBSITE_TOKEN_FOUND:     "WEBSITE_TOKEN_FOUND",
  WEBSITE_TOKEN_NOT_FOUND: "WEBSITE_TOKEN_NOT_FOUND",
  WEBSITE_TOKEN_EXPIRED:   "WEBSITE_TOKEN_EXPIRED",
  WEBSITE_CHECK_BLOCKED:   "WEBSITE_CHECK_BLOCKED",

  // Claim status transitions
  STATUS_TO_IN_REVIEW:    "STATUS_TO_IN_REVIEW",
  STATUS_TO_APPROVED:     "STATUS_TO_APPROVED",
  STATUS_TO_REJECTED:     "STATUS_TO_REJECTED",
  STATUS_TO_PENDING:      "STATUS_TO_PENDING",

  // Legacy — keep for backward compat with existing audit log entries
  STATUS_TO_LIMITED:      "STATUS_TO_LIMITED",
  STATUS_TO_VERIFIED:     "STATUS_TO_VERIFIED",
  STATUS_TO_SUSPENDED:    "STATUS_TO_SUSPENDED",

  // Support submission path
  CLAIM_SUPPORT_SUBMITTED: "CLAIM_SUPPORT_SUBMITTED",

  // Email OTP flow
  OTP_SENT:              "OTP_SENT",
  OTP_RESEND_BLOCKED:    "OTP_RESEND_BLOCKED",
  OTP_INVALID:           "OTP_INVALID",
  OTP_VERIFY_FROZEN:     "OTP_VERIFY_FROZEN",
  OTP_CONFIRMED:         "OTP_CONFIRMED",

  // Renewal flow
  RENEWAL_REMINDER_SENT:        "RENEWAL_REMINDER_SENT",
  RENEWAL_TOKEN_GENERATED:      "RENEWAL_TOKEN_GENERATED",
  RENEWAL_TOKEN_VERIFIED:       "RENEWAL_TOKEN_VERIFIED",
  RENEWAL_APPROVED:             "RENEWAL_APPROVED",
  RENEWAL_REJECTED:             "RENEWAL_REJECTED",
  RENEWAL_EXPIRED:              "RENEWAL_EXPIRED",

  // Internal admin — claim review
  INTERNAL_CLAIM_APPROVED:      "INTERNAL_CLAIM_APPROVED",
  INTERNAL_CLAIM_REJECTED:      "INTERNAL_CLAIM_REJECTED",
  INTERNAL_CLAIM_FLAGGED:       "INTERNAL_CLAIM_FLAGGED",
  INTERNAL_COOLDOWN_APPLIED:    "INTERNAL_COOLDOWN_APPLIED",
  INTERNAL_RENEWAL_REVIEWED:    "INTERNAL_RENEWAL_REVIEWED",
  INTERNAL_ACCESS_REMOVED:      "INTERNAL_ACCESS_REMOVED",

  // Internal admin — document review
  INTERNAL_DOCUMENT_REVIEWED:   "INTERNAL_DOCUMENT_REVIEWED",
  INTERNAL_INTAKE_SUBMITTED:    "INTERNAL_INTAKE_SUBMITTED",
  INTERNAL_AI_MAPPING_RUN:      "INTERNAL_AI_MAPPING_RUN",
  INTERNAL_AI_MAPPING_ACCEPTED: "INTERNAL_AI_MAPPING_ACCEPTED",
  INTERNAL_DATA_PUBLISHED:      "INTERNAL_DATA_PUBLISHED",
  INTERNAL_DOCUMENT_FAILED:     "INTERNAL_DOCUMENT_FAILED",
  INTERNAL_SOURCE_CANDIDATE_SUBMITTED: "INTERNAL_SOURCE_CANDIDATE_SUBMITTED",
  SOURCE_INGESTION_PREVIEW_CAPTURED: "SOURCE_INGESTION_PREVIEW_CAPTURED",

  // Member management (VERIFIED admin actions)
  INVITE_CREATED:         "INVITE_CREATED",
  INVITE_ACCEPTED:        "INVITE_ACCEPTED",
  INVITE_EXPIRED:         "INVITE_EXPIRED",
  INVITE_REVOKED:         "INVITE_REVOKED",
  MEMBER_REVOKED:         "MEMBER_REVOKED",
  MEMBER_VERIFIED:        "MEMBER_VERIFIED",
  DOCUMENT_APPROVED_BY_VERIFIED: "DOCUMENT_APPROVED_BY_VERIFIED",
  DOCUMENT_REJECTED_BY_VERIFIED: "DOCUMENT_REJECTED_BY_VERIFIED",
  ADMIN_DESA_STRUCTURED_SUBMITTED: "ADMIN_DESA_STRUCTURED_SUBMITTED",

  // Fake report
  FAKE_ADMIN_REPORT_SUBMITTED:   "FAKE_ADMIN_REPORT_SUBMITTED",
  ADMIN_CLAIM_FLAGGED_BY_PUBLIC: "ADMIN_CLAIM_FLAGGED_BY_PUBLIC",
} as const;

export type AuditEventType = typeof AUDIT_EVENT[keyof typeof AUDIT_EVENT];
